### ISSUE TITLE
Grafana dashboard variable queries are failing when using proxy

### ISSUE THREAD

**Issue by anoop2503** [prometheus-community/prom-label-proxy#37] opened 2020-07-20 08:34 UTC
Hi,

I have enabled the the proxy by running docker command like below.

docker run -p8080:8080 quay.io/coreos/prom-label-proxy:v0.1.0 --insecure-listen-address=0.0.0.0:8080 --upstream=http://prometheus.test.com --label=environment

This is working fine and I can see the data in the dashboard when I point the datasource to this proxy endpoint.

However, the dashboard variable queries (variable section in dashboard settings) are failing with following error alert
Template variables could not be initialized: undefined

When I check the request details in network (developer console in browser), I can see the request is failing with 404 error. However, if I run the same query without proxy, I am getting the response. No difference in the requests.

See the HTTP request details below:

With Proxy: http://grafana.test.com/api/datasources/proxy/636/api/v1/series?match[]=container_memory_usage_bytes&start=1595232914&end=1595233214

Without Proxy: http://grafana.test.com/api/datasources/proxy/641/api/v1/series?match[]=container_memory_usage_bytes&start=1595232884&end=1595233184

Thanks

**Comment by dongyingbo** [comment] 2020-07-28 06:55
@anoop2503 
It is because `series` endpoint is not exposed by the proxy. See **https://github.com/prometheus-community/prom-label-proxy/blob/master/injectproxy/routes.go#L43**

You can find out the exposed endpoints from the following piece of code.
```
	mux.Handle("/federate", enforceMethods(r.federate, "GET"))
	mux.Handle("/api/v1/query", enforceMethods(r.query, "GET", "POST"))
	mux.Handle("/api/v1/query_range", enforceMethods(r.query, "GET", "POST"))
	mux.Handle("/api/v1/alerts", enforceMethods(r.noop, "GET"))
	mux.Handle("/api/v1/rules", enforceMethods(r.noop, "GET"))
	mux.Handle("/api/v2/silences", enforceMethods(r.silences, "GET", "POST"))
	mux.Handle("/api/v2/silences/", enforceMethods(r.silences, "GET", "POST"))
```

**Comment by anoop2503** [comment] 2020-08-04 13:34
Any specific reason why the "series" endpoint is not exposed by the proxy? Any idea?

**Comment by simonpasquier** [comment] 2020-08-12 15:10
> Any specific reason why the "series" endpoint is not exposed by the proxy? Any idea?

I guess we never had the need for it. But I don't see why it couldn't be added.

cc @lilic @paulfantom @s-urbaniak

**Comment by anoop2503** [comment] 2020-08-16 06:07
I think we definitely need this, since we will be using the variables on
Grafana dashboards. This mechanism currently not working as the variable
queries are not working with prom-label-proxy.

Another issue what I found was the Grafana alerting is not working when
using prom-label-proxy. Even the test rule is failing.

**Comment by s-urbaniak** [comment] 2020-08-17 06:52
prom-label-proxy was envisioned to rely on enforcing a concrete label to underlying queries. building on top of this you can configure a tenancy model based i.e. on namespaces if you started the proxy with `--label=namespace`. If there is a way to

a) enforce a label in the series endpoint API and
b) your client is able to force-inject a label

then this is definitely a nice addition. From your example above and taking the namespace label your query would have to look like http://grafana.test.com/api/datasources/proxy/636/api/v1/series?match[]=container_memory_usage_bytes&start=1595232914&end=1595233214&namespace=foo

would translate to `match[]=container_memory_usage_bytes{namespace="foo"}`.

I am not sure, however, if grafana is able to force-inject such a parameter and where it would get it from. But from the perspective of prom-label-proxy this would certainly be a nice addtion :+1:

**Comment by dongyingbo** [comment] 2020-08-19 04:02
I created another proxy https://github.com/IBM/ibm-grafana-ocpthanos-proxy if you are interested.

**Comment by dongyingbo** [comment] 2020-09-01 05:38
I created another proxy https://github.com/IBM/ibm-grafana-ocpthanos-proxy. Instead of being deployed as Prometheus/thanos-querier sidecar it will be deployed as sidecar of Grafana.

**Comment by randrusiak** [comment] 2021-04-19 07:27
Does anyone know when it will be handled? 
Currently, I'm testing prom-label-proxy v0.3.0-rc.0-ext1 which was releases unofficially probably by bwplotka and this version allow to enable label apis (--enable-label-apis). But it still doesn't work because /api/v1/series returns empty data: {"status":"success","data":[]}. It would be easier to create PR if changes from v0.3.0-rc.0-ext1 version will be published. 

I think this feature is crucial because so many people using grafana for visualising metrics. It's a blocker for me to start using multi-tenancy.

**Comment by randrusiak** [comment] 2021-04-19 11:19
I've tested the latest image quay.io/prometheuscommunity/prom-label-proxy:master (925ddcd144e6) and everything works as expected. I hope the stable version will be released soon.

**Comment by m-yosefpor** [comment] 2021-09-01 11:15
I tested with quay.io/prometheuscommunity/prom-label-proxy:master and `--enable-label-apis` flag but it's not working yet.

```
curl 'http://prom-label-proxy/api/v1/series' --data-urlencode 'match[]=up{namespace="sth"}'
Bad request. The "namespace" query parameter must be provided.
```

```
curl 'http://thanos-querier-custom.openshift-monitoring.svc.cluster.local:9095/api/v1/series?namespace="sthelse"' --data-urlencode 'match[]=up{namespace="sth"}'
404 page not found
```

having query parameter in `/api/v1/series` results in `404` (even if I directly send requests to prometheus).

**Comment by m-yosefpor** [comment] 2021-09-04 12:02
Found the issue with prom-label-proxy, when running with `--enable-label-apis` queries such as 
```
curl 'http://prom-label-proxy/api/v1/series?namespace=sth'
```
will work, however, queries which already have `match[]` will recieve 404 from label-proxy, such as 
```
curl 'http:/prom-label-proxy/api/v1/series?namespace=sth' --data-urlencode 'match[]=up{namespace="sth"}'
404 page not found
```

However this query works if sent directly to prometheus.

**Comment by bwplotka** [comment] 2021-09-04 18:06
Hey, thanks for reporting. 

Not sure why you mentioned `--enable-label-apis`. `series ` is not a label API. 

Otherwise, if you cannot provide any other query parameter, it sounds like a bug, let's investigate.

**Comment by bwplotka** [comment] 2021-09-04 18:09
Also it's confusing to report your parameter not handling well on this particular issue. 

Series was added (https://github.com/prometheus-community/prom-label-proxy/blob/master/injectproxy/routes.go#L146) so let's close this and create another one to focus on your problem @m-yosefpor WDYT? (:

**Comment by bwplotka** [comment] 2021-09-04 18:09
Can you confirm that series works with namespace param but without any extra `match` param? but with it, it does not?

**Closed by bwplotka** 2021-09-04 18:09 UTC

**Comment by m-yosefpor** [comment] 2021-09-04 18:36
Thanks @bwplotka I can confirm both `/api/v1/series` and `/api/v1/labels` work with or without extra `match` parameters when requests sent to prom-label-proxy directly (also grafana integration works fine) . Excuse me for my incorrect conclusion. You have already added https://github.com/prometheus-community/prom-label-proxy/blob/master/injectproxy/routes.go#L376 in `func injectMatcher` to handle extra `match` params . So this issue should be closed. 

However as it is a common pattern to have kube-rbac-proxy in front of it, the issue appears when requests sent to kube-rbac-proxy first and forwarded to prom-label-proxy. I should increase the log level of both to figure out if the issue is related to kube-rbac-proxy itself (and follow the issue with them), or if kube-rbac-proxy is injecting sth (into query params, etc) which causes prom-label-proxy to respond 404 due to a bug.

I will create another issue later if the issue was related to prom-label-proxy.
